server:
  port: 7090

spring:
  kafka:
    producer:
      value-serializer: com.github.ch629.kafkademo.serializers.KafkaProtobufSerializer
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
      group-id: group1
      value-deserializer: com.github.ch629.kafkademo.serializers.KafkaProtobufDeserializer
      auto-offset-reset: earliest
    listener:
      ack-mode: manual_immediate
    streams:
      auto-startup: false
  redis:
    host: localhost:6379
